name: Auto deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  # test:
  #   name: Run tests
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #       node-version: [18, 20]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 20

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Start tests
  #       run: npm test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:prod

      - name: Start deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist